### PR TITLE
Better Bot State System Update

### PR DESCRIPTION
**Pull request by T-Rizzle12**
The new state system is great, but adding and creating new states is very hard and time-consuming. Using my newfound knowledge about metatables, I am creating a new state class that will allow me to create new states much more efficiently than before. Essentially, I recreated the Action system used by NextBots in Valve games such as Left 4 Dead and TF2. This will allow multiple states to run at once and even allow the bots to respond to hook events based on the active action. I have also updated the client-side vgui to make it easier to find and register weapons since it will now show the fancy name and which addon the weapon came from. I have also made so bug fixes that will hopefully make the gaming experience better. I have also refactored the code to make it much more organized than it was before. A new hook TRizzleBotInitialized was added which is called every time the addon finishes initializing making it a great hook to use when want to register weapons or override parts of the addon. You may notice that some of the old functions are still in the addon. This is because I want to give some time for people to update their code, "me included," before cleaning up the rest of the code.

Change Log:
- Recreated the Action system used in TF2 and L4D2, as a result, the code is much faster than before
- Made the bot have separate interfaces that manage aiming, ladders, and the bot's vision
- Made the code now use custom Pathfollow classes for pathfinding
- Bots will now move to the player they are trying to heal and will now look further for potential heal targets
- Bots will now use ChasePath when following their owner and group leader
- Fixed a bug where the bot thought it was a good idea to use its secondary attack even if it would hit a wall
- Changed the client side vgui to make it easier to identify weapons since it used to only display the weapon's classname
- Improved bot respawn logic
- Improved bot healing logic
- Moved door-opening and obstacle-breaking logic into the Pathfollower class
- Fixed a bug where saying the bot's name without a command would create errors in the console
- Improved how the bot selects enemies
- Optimized how the bot selects enemies
- Bots now remember the last time they took damage from an enemy
- Bots now consider enemies that injured them recently immediate threats
- Changed multiple range checks to use math.huge instead of a large number, "Example: 1000000 is now math.huge"
- Changed how group leaders search for enemies
- Added new globals for the addon to use
- Changed the bot update tickrate from 2 to 7 since it was causing the bot to run too often
- Added new function UpdateLookingAroundForEnemies, this is used by the Action system to make the bot look for enemies as well as aim at them
- Made it so the bot will only fling its aim when blinded if the bot is in combat
- Added some optimizations to the vision interface
- "Hopefully" improved how the bot selects weapons
- Added a version of GetTBotDistancePriority that accepts a string instead of a weapon
- Changed the code to use ents.Iterator and player.Iterator
- Changed IsThreatFiringAtMe to check in the NPC aiming at a bot has an actual weapon
- Changed multiple function to check and update the new interfaces
- Added new hook called TRizzleBotInitialized, this is called once this addon has finished being Initialized. Other modders can use this to override or add onto this addon.
- Changed how the bot internally defines its maximum forwardMovement and strafeMovement to be 10,000. This is consistent with the cl_forwardspeed and cl_sidespeed ConVars, which allows all movement hooks to properly affect the bot.
- Made some changes to GetFogObscuredRatio to accept lengthSqr instead of length in order to optimize it
- Bots now give themselves the maximum stored ammo for a weapon when they spawn it in
- Bots will now reload weapons based on whether they have visible enemies or not and on the amount of ammo they have left in the clip while in combat
- Added a new parameter to the TBotWeapon system, ReloadsSingly, This tells the bot that the entered weapon reloads one bullet at a time. This parameter is optional and will default to true if the weapon type is set to Shotgun and false for any other weapon types
- Fixed some inconsistencies in the code
- Updated vgui to reflect the new ReloadsSingly parameter
- Bots will now more intelligently pick their next backup weapon based on the weapon they were trying to use
- Reverted a change made in FindSpots since it was causing the bots to run nearby enemies when attempting to reload weapons in cover 

Known Issues:
- Bots can't tell the difference between projectile and tracer, "bullet," weapons

### CODE REVIEW

**Review by T-Rizzle12 — COMMENTED** [review]
- Recreated the Action system used in TF2 and L4D2, as a result, the code is much faster than before
- Made the bot have separate interfaces that manage aiming, ladders, and the bot's vision
- Made the code now use custom Pathfollow classes for pathfinding
- Bots will now move to the player they are trying to heal and will now look further for potential heal targets
- Bots will now use ChasePath when following their owner and group leader
- Fixed a bug where the bot thought it was a good idea to use its secondary attack even if it would hit a wall
- Improved bot respawn logic
- Improved bot healing logic
- Moved door-opening and obstacle-breaking logic into the Pathfollower class
- Fixed a bug where saying the bot's name without a command would create errors in the console
- Improved how the bot selects enemies
- Optimized how the bot selects enemies
- Bots now remember the last time they took damage from an enemy
- Bots now consider enemies that injured them recently immediate threats
- Changed multiple range checks to use math.huge instead of a large number, "Example: 1000000 is now math.huge"
- Changed how group leaders search for enemies
- Added new globals for the addon to use
- Change the bot update tickrate from 2 to 7 since it was causing the bot to run too often
- Added new function UpdateLookingAroundForEnemies, this is used by the Action system to make the bot look for enemies as well as aim at them
- Made it so the bot will only fling its aim when blinded if the bot is in combat
- Added some optimizations to the vision interface
- "Hopefully" improved how the bot selects weapons
- Added a version of GetTBotDistancePriority that accepts a string instead of a weapon
- Changed the code to use ents.Iterator and player.Iterator
- Changed IsThreatFiringAtMe to check in the NPC aiming at a bot has an actual weapon
- Changed multiple function to check and update the new interfaces
- Added new hook called TRizzleBotInitialized, this is called once this addon has finished being Initialized. Other modders can use this to override or add onto this addon.

**Review by T-Rizzle12 — COMMENTED** [review]
- Changed how the bot internally defines its maximum forwardMovement and strafeMovement to either be the bot's run speed, max speed, or 10,000. The bot will now pick the largest number to allow all movement hooks to properly affect the bot.

**Review by T-Rizzle12 — COMMENTED** [review]
- Changed the default forward and strafe speed to 10000 since that is the default movement speed as defined in Gmod's ConVars cl_forwardspeed and cl_sidespeed

**Review by T-Rizzle12 — COMMENTED** [review]
- Added IsOnLadder to the Locomotion interface
- Added IsNotMoving to the Locomotion interface
- Fixed some inconsistencies in the code

**Review by T-Rizzle12 — COMMENTED** [review]
- Registered TBotBody, TBotLocomotion, and TBotVision to the base class system so they can be used to create custom versions for other gamemodes

**Review by T-Rizzle12 — COMMENTED** [review]
- Fixed a bug in TBotRetreatPath causing it not to use the retreat range in the RetreatPathBuilder Object

**Review by T-Rizzle12 — COMMENTED** [review]
- Fixed a bug in TBotRetreatPath, where the bot would attempt to call a depreciated function

**Review by T-Rizzle12 — COMMENTED** [review]
- Fixed retreat path attempting to index an invalid variable

**Review by T-Rizzle12 — COMMENTED** [review]
- Bots now give themselves the maximum stored ammo for a weapon when they spawn it in
- Bots will now reload weapons based on whether they have visible enemies or not and on the amount of ammo they have left in the clip

**Review by T-Rizzle12 — COMMENTED** [review]
- Added a new parameter to the TBotWeapon system, ReloadsSingly, This tells the bot that the entered weapon reloads one bullet at a time. This parameter is optional and will default to true if the weapon type is set to Shotgun and false for any other weapon types
- Fixed some inconsistencies in the code
- Updated vgui to reflect the new ReloadsSingly parameter
- Updated Actions to use the new ReloadsSingly parameter when conducting reload checks

**Review by T-Rizzle12 — COMMENTED** [review]
- Bots will how more intelligently pick their next backup weapon based on the weapon they were trying to use

**Review by T-Rizzle12 — COMMENTED** [review]
- Fixed a typo

**Review by T-Rizzle12 — COMMENTED** [review]
- Updated TBotRetreatPath to be more consistent with the one used in Valve's games

**Comment by T-Rizzle12** [comment]
That should be everything, just a few tests I want to run then this update its finally finished! 🎉

**Review by T-Rizzle12 — COMMENTED** [review]
- Slight change to how the bot picks a weapon when destroying a breakable object

**Comment by T-Rizzle12** [comment]
I'm still working on ironing out some things, but the update should be out soon.

**Comment by T-Rizzle12** [comment]
Now that I think about it, I should move the HandleButtons function into the Locomotion interface before releasing this update.

**Review by T-Rizzle12 — COMMENTED** [review]
- Cleaned up some code
- Moved HandleButtons code into TBotLocomotion Interface

**Review by T-Rizzle12 — COMMENTED** [review]
- Cleaned up more code
- Fixed IsCrossingLineOfFire not checking the bot's vision interface
- Fixed the TBotRegisterWeapon console command not accepting the ReloadsSingly parameter
- Replaced some for loops to use player.Iterator since its faster

**Review by T-Rizzle12 — COMMENTED** [review]
- Cleaned up some code
- Fixed actions removed by the GC system not unregistering themselves from the hook system

**Review by T-Rizzle12 — COMMENTED** [review]
- Fixed the bot attempting to use the secondary attack of a weapon even when it's out of ammo for said secondary attack
- Fixed the bot not selecting another weapon if its current weapon was removed for some reason in the TBotMainAction

**Review by T-Rizzle12 — COMMENTED** [review]
- Made a minor optimization

**Review by T-Rizzle12 — COMMENTED** [review]
- Fixed a bug in the think interval being sent to the action system
- Removed some unused code
- Fixed a bug when the bot's owner leaves the game
- Fixed a bug where the alert chat command would do nothing

**Review by T-Rizzle12 — COMMENTED** [review]
- Fixed a regression caused by one of my bug fixes in the bot's fire weapon code

**Review by T-Rizzle12 — COMMENTED** [review]
- Restored the code that affects the bot's fire rates using the think interval
- Fixed the bot not using the locomotion interface inside of the TRizzleBotRangeCheck cost function

**Comment by T-Rizzle12** [comment]
- Fixed TBotChasePath not using the locomotion interface when predicting where its chase target is moving next

**Review by T-Rizzle12 — COMMENTED** [review]
Description:

Improved Pathfinding Efficiency: Replaced the previous while true loop with a more optimized loop that has an explicit end condition. This change significantly reduces overhead in the bot pathfinding logic, leading to smoother and faster performance.
Impact: Player bots now calculate paths more efficiently, resulting in faster responses and reduced lag during pathfinding operations.
Performance Gains: Benchmarks show a noticeable decrease in CPU usage when multiple bots are active, especially in complex environments.
Technical Details:

JIT Optimization: The updated loop structure allows LuaJIT to better optimize the pathfinding process by improving predictability and reducing branching.
Code Simplification: The logic is now cleaner and easier to maintain without compromising performance.

I will note that there will still be lag on large maps, but its better than before.

**Comment by T-Rizzle12** [comment]
There were a lot more issues than expected, it will take me a little longer to iron out said issues. Some issues that are not game breaking will be addressed in the next update.

**Comment by T-Rizzle12** [comment]
I am finishing up some final changes and will finally release this update!

**Comment by T-Rizzle12** [comment]
I also will be making changes to the client side vgui to make it easier for players to register weapons!

**Comment by T-Rizzle12** [comment]
I'm just going to do some final tests for the updated client-side vgui and this update is ready to go!

**Review by T-Rizzle12 — COMMENTED** [review]
- Removed a redundant C call
- Removed table.Empty calls since it's slower than creating a new table
- Removed some redundant comments
- Changed the client side vgui to make it easier to identify weapons since it used to only display the weapon's classname

**Comment by hmaswn** [comment]
> Description:
> 
> Improved Pathfinding Efficiency: Replaced the previous while true loop with a more optimized loop that has an explicit end condition. This change significantly reduces overhead in the bot pathfinding logic, leading to smoother and faster performance. Impact: Player bots now calculate paths more efficiently, resulting in faster responses and reduced lag during pathfinding operations. Performance Gains: Benchmarks show a noticeable decrease in CPU usage when multiple bots are active, especially in complex environments. Technical Details:
> 
> JIT Optimization: The updated loop structure allows LuaJIT to better optimize the pathfinding process by improving predictability and reducing branching. Code Simplification: The logic is now cleaner and easier to maintain without compromising performance.
> 
> I will note that there will still be lag on large maps, but its better than before.

Could I ask what your cpu is??

**Comment by T-Rizzle12** [comment]
> > Description:
> > Improved Pathfinding Efficiency: Replaced the previous while true loop with a more optimized loop that has an explicit end condition. This change significantly reduces overhead in the bot pathfinding logic, leading to smoother and faster performance. Impact: Player bots now calculate paths more efficiently, resulting in faster responses and reduced lag during pathfinding operations. Performance Gains: Benchmarks show a noticeable decrease in CPU usage when multiple bots are active, especially in complex environments. Technical Details:
> > JIT Optimization: The updated loop structure allows LuaJIT to better optimize the pathfinding process by improving predictability and reducing branching. Code Simplification: The logic is now cleaner and easier to maintain without compromising performance.
> > I will note that there will still be lag on large maps, but its better than before.
> 
> Could I ask what your cpu is??
@hmaswn
Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz   2.50 GHz

**Pull request merged**
