### PR TITLE
Bot Senses and Memory Update

### PR DESCRIPTION
**Pull request by T-Rizzle12**
There were a few things I wanted to change about the bot. I wanted to give the bot a LOS, “Line of Sight,” a Hearing Interface and a Memory Interface. While I was creating said interfaces I also optimized and improved the code in the addon. As well as fixing some bugs.

For the Vision interface, it will check if the enemy is visible and in the bot's FOV, "Field Of View". The bot’s LOS will be affected by fog.

For the Hearing interface this allows the bot to "hear" enemies that are behind it. I use this to make the bot hear enemies approaching from behind the bot. Mostly to help with the fact the bot can’t see behind it anymore.

For the Memory Interface, this is where the bot will keep track of enemies it has seen before and check if they are still visible, “it will use the old visibility checks when checking LOS.”

Change Log:
- Added bot Vision Interface, the bot can no longer see behind it
- Added bot Hearing Interface, the bot can hear enemys nearby it and through walls
- Made the bot react to damage taken from an enemy
- The bot will prioritize enemies in its LOS unless an enemy on the bots known enemy list is closer than 200 HUs
- Added new Function IsHiddenByFog
- Changed current client file to a universal client file
- Increased the time between FireWeaponInterval, "when the bot presses its attack key"
- Made the bots cooldown for pressing buttons when using its medkit to use FireWeaponInterval
- Fixed a bug where the bot would use shotguns at long range and snipers at close range
- Added LookTarget, LookTargetTime, and LookTargetPriority
- LookTarget is the position the bot is trying to look at
- LookTargetTime is how long the bot should look at said position
- LookTargetPriority is how important the current position is. This allows me to set climbing up ladders to be more important than aiming at enemies
- Major optimization to weapon selection system
- Optimization to think function, it is now split into 2 functions, upkeep is run often and has important functions while update has functions that don’t need to be run every second
- Major optimization to distance checks, they now use lengthSqr instead on length
- Partial fix to the bot randomly jumping on stairs
- Changed medkit use interval to 0.5 seconds
- Moved the flashlight check to update think, since it effects every bot
- Moved head detection trace to upkeep function
- Fixed a potential bug where bot think timers would run on real players and/or bots that are not apart of my addon
- Added new function TBotBlind this function will be used to make the bot blind for the specified amount of time
- Limited how often the bot can swap it’s active weapon
- Changed how the bot presses its buttons, this new method allows me to tell the bot to push buttons without having it be in the start command hook
- Fixed the new think function :)
- The bot will no longer spam its attack button when an enemy is within melee distance, it caused the bot to accidentally attack teammates
- Replaced my think system with Valve’s bot think system, "this optimized code by 40%"
- Fixed a bug in PointWithinCursor sometimes causing the bot to press its IN_ATTACK when facing the opposite direction from its current enemy
- Optimized PointWithinCursor by doing the trace check last, "The trace check is the most expensive part, if the function will return false with the cheaper methods its should"
- Improved ladder path creation allowing me to remove the hack I used for it
- Removed IsValid checks from ShouldDropDown and ShouldJump since it caused them to always return false
- Changed how the bot looks at the path it’s following
- Partially changed how waypoints are created
- Changed Owner to TBotOwner, since Owner is used internally by the engine
- Added IsDoorOpen, the bot will no longer open doors if it is already open
- Fixed the bot only climbing the highest ladder if the bot has to climb up two or more ladders that share a nav_area to get on and off said ladders
- Made some fixes to the hybrid version of PathFollower
- Added functions to find hiding spots, “currently not used”
- Changed how the bot presses its movement keys, "WASD keys"
- Added new function GetDefaultFOV, "returns the default FOV of the bot"

### CODE REVIEW

**Review by T-Rizzle12 — COMMENTED** [review]
- Added bot Vision Interface, the bot can no longer see behind it
- Made the bot react to damage taken from an enemy
- The bot will prioritize enemies in its LOS unless an enemy on the bots known enemy list is closer than 200 HUs

**Comment by T-Rizzle12** [comment]
- Added the bot Hearing Interface

**Comment by strubium** [comment]
I gotta say, you're popping off this morning

**Comment by strubium** [comment]
> > I gotta say, you're popping off this morning
> 
> Most of the recent commits are small changes. Since you can’t really save your work in GitHub I have to upload a commit that isn’t ready.

Yeah, but all of them add up. Good work!

**Comment by T-Rizzle12** [comment]
> > > I gotta say, you're popping off this morning
> > 
> > 
> > Most of the recent commits are small changes. Since you can’t really save your work in GitHub I have to upload a commit that isn’t ready.
> 
> Yeah, but all of them add up. Good work!

I know, i'm going on vacation for the next week so progress will be slower than usual

**Comment by T-Rizzle12** [comment]
Sigh, finally got the code checker adjusted to the right settings.

**Comment by strubium** [comment]
> Sigh, finally got the code checker adjusted to the right settings. Another cool thing about GitHub actions is when you clone the repository the workflow file won’t be downloaded as well.

ah fuc

not helpful

**Review by T-Rizzle12 — COMMENTED** [review]
- Increased the time between FireWeaponInterval
- Made the bots cooldown for pressing buttons when using its medkit to use FireWeaponInterval
- Fixed a bug where the bot would use shotguns at long range and snipers at close range
- Fixed a error in the hearing interface

**Comment by T-Rizzle12** [comment]
- Added new Function IsHiddenByFog, “currently not used”

**Review by T-Rizzle12 — COMMENTED** [review]
- Implemented new aiming system
- Major optimization to weapon selection system
- Optimization to think function, it is now split into 2 functions, upkeep is run often and has important functions while update has functions that don’t need to be run every second
- Major optimization to distance checks, they now use lengthSqr instead on length
- Partial fix to the bot randomly jumping on stairs
- Changed medkit use interval to 0.5 seconds
- Moved the flashlight check to a think hook run every 0.15 seconds, since it effects every bot

**Comment by T-Rizzle12** [comment]
- Cleaned up some code

**Comment by T-Rizzle12** [comment]
- Moved head detection trace to upkeep function
- Fixed a potential bug where bot think timers would run on real players and/or bots that are not apart of my addon
- Added a missing IsValid check

**Comment by strubium** [comment]
> * Removed TRizzleBotFogCheck net message since I have figured out how to grab fog parameters on the server
How? 

Also, thanks for your help on my issue

**Review by T-Rizzle12 — COMMENTED** [review]
- Cleaned up some code

**Comment by strubium** [comment]
> > > * Removed TRizzleBotFogCheck net message since I have figured out how to grab fog parameters on the server
> > >   How?
> > 
> > 
> > Also, thanks for your help on my issue
> 
> I can grab the fog entity and read the variables off of it since FacePunch gave it NetworkVars.

Nice!

**Comment by T-Rizzle12** [comment]
I was looking through CS:GO source code when I just noticed that valve bots upkeep function was run EVERY FRAME. The update function appears to be run about 3 to 4 frames. The fact that valve bots are very optimized and run this often is crazy. After some thorough investigation, tons of functions are run during the upkeep and update functions. It doesn’t seem like a lot, but when you think about it. Imagine 32 valve bots all running at the same time, this includes repathing every 0.1 seconds. Yet most players experience little to no lag during this entire process. After or during this update I may attempt to experiment with this.

**Review by T-Rizzle12 — COMMENTED** [review]
- Fixed the bot looking at a position after the amount of time the bot was told to look at it
- Fixed the new think function :)
- The bot will no longer spam its attack button when an enemy is within melee distance, it caused the bot to accidentally attack teammates
- Fixed the bot not jumping off of ladders
- Fixed the bot not gap jumping
TODO: The game will randomly lag. I currently have no idea what could be the cause of the lag, it may be pathfinding related, but I still have to check. Other than that the Valve’s bot think system is surprisingly optimized.

**Comment by T-Rizzle12** [comment]
- Fixed IsAbleToSee using incorrect fog distance

**Review by T-Rizzle12 — COMMENTED** [review]
- Added IsValid checks to ShouldDropDown and ShouldJump functions since they somehow had the chance to be given invalid vectors
Test Notes: It appears that I have fixed the random lag. Everything appears to work as expected. 
TODO: The bot partially lags the game while in combat, “about 10 to 20 frame loss per bot,” I currently don’t know the cause of the lag, but I will work on optimization. I will look into CS:GO source code and check how Valve made their combat code so optimized.

**Comment by T-Rizzle12** [comment]
- Updated TRizzleCreateBot console command, because I forgot to do it when I updated its max parameters

**Comment by T-Rizzle12** [comment]
- Removed old pathfinding code

**Review by T-Rizzle12 — COMMENTED** [review]
- Optimization to TBotFindClosestEnemy and TBotCheckEnemyList functions
- Removed some redundant if statements
- Moved UpdateAim function to StartCommand hook
- Moved some aiming code to StartCommand hook

**Comment by T-Rizzle12** [comment]
- Added some comments
- Removed a redundant statement in attack code
- Fixed a bug in IsAbleToSee not checking both the EyePos and WorldSpaceCenter
- Fixed a bug in PointWithinCursor sometimes causing the bot to press its IN_ATTACK when facing the opposite direction from its current enemy
- Optimized PointWithinCursor by doing the trace check last, "The trace check is the most expensive part, if the function will return false with the cheaper methods its should"

**Review by T-Rizzle12 — COMMENTED** [review]
- Fixed the bug fix for PointWithinCursor causing the bot only being allowed to shoot of the shot would miss, “basically if fixed the bot only pressing it’s attack button only if the shot would miss.”
- Fixed the bot being able to see enemies when its blind

**Comment by T-Rizzle12** [comment]
- Removed redundant variable
- Added a comment
- Improved bot weapon selection while in combat

**Comment by strubium** [comment]
> * Fixed the bot being able to see enemies when its blind

lmao, that makes sense. 

Would SWEP flashbangs (in the future at least) be able to blind bots? That would be really cool!

**Comment by T-Rizzle12** [comment]
> > * Fixed the bot being able to see enemies when its blind
> 
> lmao, that makes sense.
> 
> Would SWEP flashbangs (in the future at least) be able to blind bots? That would be really cool!

I would have to manually add support, but yes.

**Comment by T-Rizzle12** [comment]
Every interface has been successfully added, so after some testing and debugging I will release this update.

**Comment by strubium** [comment]
> Every interface has been successfully added, so after some testing and debugging I will release this update.

Awesome!

**Comment by T-Rizzle12** [comment]
Test 1 Notes:
Improved the bot ladder path creation. It’s a lot better than before and even looks nicer at times. It also allowed me to remove the hack I added to get the bot to properly climb said ladder. I fixed the bug where the bot couldn’t detect drop-down anymore. I still have to test each interface and I should also test how long each update and upkeep event lasts.

**Comment by strubium** [comment]
> @T-Rizzle12, this is a reminder to release the addon on the steam workshop once this update is released.

YES! This is great!

**Comment by T-Rizzle12** [comment]
I expect to release the update this week. I have found a couple of bugs that need fixing currently.

**Review by T-Rizzle12 — COMMENTED** [review]
- Changed Owner to TBotOwner, since Owner is used internally by the engine
- Added IsDoorOpen, the bot will no longer open doors if it is already open
- Fixed the bot only climbing the highest ladder if the bot has to climb up two or more ladders that share a nav_area to get on and off said ladders, “there is now a new bug that got created if the bot repaths an error will appear, I don’t know the cause yet, but I will figure it out.”

**Comment by T-Rizzle12** [comment]
- Added PathLength, This is how long the current path is.
- Made some fixes to the hybrid version of PathFollower

**Comment by T-Rizzle12** [comment]
I just figured out how to get the bot to turn while driving vehicles, I may be able to add vehicle support.

**Comment by T-Rizzle12** [comment]
- Changed path creation to not adjust drop-downs if the next area is marked as a jump area

**Comment by T-Rizzle12** [comment]
All I have to do now is test the new code, make sure everything is optimized, and we should be good to go.

**Comment by T-Rizzle12** [comment]
- Added functions to find hiding spots, “currently not used and not finished”

**Comment by T-Rizzle12** [comment]
- Fixed format of new code
- Removed PathLength since I created a function to replace it

**Comment by T-Rizzle12** [comment]
- Finished hiding spot detection code

**Comment by T-Rizzle12** [comment]
- Updated feature list in README.md

**Review by T-Rizzle12 — COMMENTED** [review]
- Changed how bots look at the path they are following, "also made it cheaper"
- Changed how the bot presses its movement keys, "WASD keys"
- Added new function GetDefaultFOV, "returns the default FOV of the bot"
- Moved flashlight check from a timer into the think function
- Changed the distance bots move the dropdown goal from 25HU to 75HU

**Comment by T-Rizzle12** [comment]
- Changed the distance bots move the dropdown goal back to 25HU since 75HU caused the bot to get stuck sometimes

**Comment by T-Rizzle12** [comment]
@t-rizzle-s-assistant
Merge the request please!!

**Pull request merged**
